### ISSUE TITLE
vevo videos not working

### ISSUE THREAD

**Issue by stefangomez** [0xced/XCDYouTubeKit#105]
Looks like there's a reoccurrence of #94 here. Anybody else having problems playing vevo/wmg videos?

**Comment by chawei** [comment]
yea i have the same problem here.

**Comment by chrisnolet** [comment]
Was just about to post :) I'm not getting an error this time though; just no video/sound.

**Comment by imclean** [comment]
same problem here

**Comment by Jellyfishinatrifle** [comment]
me too

**Comment by 0xced** [comment]
YouTube changed its API again. I will investigate and try to publish a new version ASAP.

**Comment by SoneeJohn** [comment]
For some odd reason my users are reporting the same issue: "Request failed: 403". I am guessing this is due, the the API change that you mentioned. However, I have not experienced this issue myself. I really hope this is fixed :+1:  :-)

**Comment by 0xced** [comment]
Yes, the 403 error stems from the API change. This only happens for protected videos though.

**Comment by martinobonfiglioli** [comment]
Now it seem back to work again, slowly

**Comment by psycotica0** [comment]
I'm seeing the same from here: the previous technique is working again. 

I don't know how to feel about it.
Suspicious, perhaps.

**Comment by nahum365** [comment]
Still not working for me. The playbackState on the MPMoviePlayer just never changes from buffering to playing.

**Comment by Cartman2000** [comment]
Yep not working either

**Comment by codaman** [comment]
Has anybody tried older versions?? Which one is previous technique

**Comment by psycotica0** [comment]
Nevermind, it's stopped working for us again too. By previous technique I just meant whatever master was using.

**Comment by psycotica0** [comment]
Perhaps related, this is youtube_dls fix https://github.com/rg3/youtube-dl/commit/a9b6b5cd15cff004b4109ab64b181fff23c10770

**Comment by codaman** [comment]
İ've tried YouTube-dl. It also cannot download vevo videos. Have you tried it

**Comment by psycotica0** [comment]
Yeah, youtube_dl works after the commit I linked to above. Before that it did not.

**Comment by psycotica0** [comment]
Doing some debugging, it seems like the problem is that we're not getting the script we need to decode the signature. Putting code into XCDYouTubeVideoOperation.m's start function that downloads a hardcoded string of http://s.ytimg.com/yts/jsbin/html5player-en_US-vfl86Quee/html5player.js, and then uses XCDYouTubePlayerScript on that string makes it work.

**Comment by psycotica0** [comment]
Still not in a good place code-style wise. Working on a patch.

**Comment by psycotica0** [comment]
Ok, even better.

In XCDYouTubeVideoOperation:start, if instead of calling `[self startNextVideoInfoRequest]`, you call `[self startRequestWithURL: watch_page]`, where watch page is the page like "http://youtube.com/watch?v=STUFFSTUFF".

The code just takes it from there. I don't know, looking at the code, why this code path never seems to come up otherwise.

**Comment by psycotica0** [comment]
Alright, the code I borrow from elsewhere in the code to make my approach work seems to have come from an error handler. It's possible that the API used to tell us we needed to sign things, whereas now it just lets us submit unsigned things and rejects us.

**Comment by psycotica0** [comment]
Alright, so I think I've traced it back to the change. It looks like there used to be a value in the response called "use_cipher_signature" that, when true, told us we needed to fetch the script to decode things. This key appears to no longer be present.

**Comment by psycotica0** [comment]
Alright, the last thing that seems to have been needed was to make it so that a playerScript with no 's' parameter isn't considered an error. Patch getting cleaned up for some sort of review.

**Comment by chrisnolet** [comment]
Awesome, thanks for digging through this!

**Comment by psycotica0** [comment]
https://github.com/0xced/XCDYouTubeKit/pull/106

**Comment by SoneeJohn** [comment]
Thanks for looking into this issue @psycotica0. I will issue an update to my users and see if it fixes the problems they have been experiencing.

**Comment by 0xced** [comment]
I'd suggest waiting for an official update, the proposed fix breaks a lot of unit tests.

**Comment by SoneeJohn** [comment]
Yeah sure, that's why the update that I issued to my users is just a beta candidate. I will do an official release when the class gets and official update.

**Comment by nahum365** [comment]
I've also submitted an update with @psycotica0's fix. I hate to be the person to ask this, but is there a expected completion date on the official update?

**Comment by objectiveCarlo** [comment]
Hi guys I have a temporary fix in my fork: https://github.com/objectiveCarlo/XCDYouTubeKit/commit/932ce56d7d3eec0a51565b0eb37e2281f21e11e4

**Comment by hodalgun** [comment]
um... not working... same problem.. ㅠ.ㅠ

**Comment by K-IOS** [comment]
I have the same problem here.
Any temporary solution to solve this ?

**Comment by chrisnolet** [comment]
I'm using @psycotica0's fix in the mean time too, although I understand that an official fix is on the way:



`pod 'XCDYouTubeKit', :git => 'https://github.com/psycotica0/XCDYouTubeKit.git', :commit => '898d3105f424ba61a11bd1c7c8c88d3dbb386e94'`








Regards,


Chris Nolet

Co-Founder at Relaunch.io




+1 (415) 483-6458




Please note: I receive my email daily at 8am. If you have an urgent matter, please call me on the number above.

**Comment by hectordominguez00** [comment]
Is there any functional fix?

**Comment by 0xced** [comment]
The `develop` branch now contains a fix for this issue. I will publish an official update once I fix the [age-restricted VEVO video](https://travis-ci.org/0xced/XCDYouTubeKit/builds/49292358) issue.

**Comment by K-IOS** [comment]
where is the develop branch ? Can you please give link for develop branch ?
